### ISSUE TITLE
[Question] For what purpose in the function "Os:follow_link()" lines:

### ISSUE THREAD

**Issue by jurikor** [pforret/bashew#19]
Hello.
It's just a question

For what purpose in the function "Os:follow_link()" lines:

```
857  [[ "$file_folder" != /* ]] && link_folder="$(cd -P "$file_folder" &> /dev/null && pwd)"
858  local symlink
859  symlink=$(readlink "$1")
860  link_folder=$(dirname "$symlink")
```

it looks pointless in the part concerning link_folder

Thanks for your feedback 
Yury

**Comment by pforret** [comment]
Hi!

The main goal (if I recall correctly) is to resolve symbolic links to their real path. I use the [basher](https://www.basher.it/) package manager and it works with symbolic links for the scripts it installs.

E.g. 
`bashew ` &rarr; `$HOME/.basher/bin/bashew` &rarr; `$HOME/.basher/cellar/packages/pforret/bashew/bashew`

so the 'real' installation path (where I could find the .env and other config files) is `$HOME/.basher/cellar/packages/pforret/bashew` and I would not find that if I just do `dirname "$0"`

**Comment by jurikor** [comment]
Hello.

> The main goal (if I recall correctly) is to resolve symbolic links to their real path. I use the [basher](https://www.basher.it/) package manager and it works with symbolic links for the scripts it installs.

That's clear.

But.
What is line 857 for? If we redefine the link_folder variable in line 860?

**Comment by pforret** [comment]
I think the technical term for that is "a bug" :-)

I fixed it now!

**Comment by pforret** [comment]
```bash
function Os:follow_link() {
  [[ ! -L "$1" ]] && echo "$1" && return 0 ## if it's not a symbolic link, return immediately
  local file_folder link_folder link_name symlink
  file_folder="$(dirname "$1")" ## check if file has absolute/relative/no path
  [[ "$file_folder" != /* ]] && file_folder="$(cd -P "$file_folder" &> /dev/null && pwd)" ## a relative path was given, resolve it
  symlink=$(readlink "$1") ## follow the link
  link_folder=$(dirname "$symlink") ## check if link has absolute/relative/no path
  [[ -z "$link_folder" ]] && link_folder="$file_folder" ## if no link path, stay in same folder
  [[ "$link_folder" == \.* ]] && link_folder="$(cd -P "$file_folder" && cd -P "$link_folder" &> /dev/null && pwd)" ## a relative link path was given, resolve it
  link_name=$(basename "$symlink")
  IO:debug "$info_icon Symbolic ln: $1 -> [$symlink]"
  Os:follow_link "$link_folder/$link_name" ## recurse
}
```

**Comment by jurikor** [comment]
Thanks for the comments )

**Comment by pforret** [comment]
> Thanks for the comments )

Thanks for pointing out the bug!!
