### ISSUE TITLE
Do not call `check_last_version` if no `.git` directory found

### ISSUE THREAD

**Issue by drmikecrowe** [pforret/bashew#8]
**Describe the bug**
When running a script in a non-git folder, you see:

```
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

**To Reproduce**
1. Run `bashew script` in your root folder
2. Execute the new script with `-h`

**Expected behavior**
No git error should occur

**Desktop (please complete the following information):**
- Shell type : bash - version 5.0.17(1)-release 
- OS Version : Distributor ID:	Ubuntu (Linux) Release:	20.10 on x86_64 
- Program: bashew 1.15.0 
- Updated: 2021-02-28 05:39

**Comment by pforret** [comment]
added a check if the script is in a git repo, before checking for updates
