### ISSUE TITLE
Add `bashew diag` to print details for bug report

### ISSUE THREAD

**Issue by drmikecrowe** [pforret/bashew#9]
**Is your feature request related to a problem? Please describe.**
`bashew -v -h` prints an interesting header.  If you tweaked it a bit, it could print what you want for bug reports

**Describe the solution you'd like**
No preference, offering as suggestion for your consideration

**Comment by pforret** [comment]
Good point.
The bug report template [bug_report.md](https://github.com/pforret/bashew/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) asks for 
(please complete the following information):

OS: [e.g. MacOS]
bash version (bash --version)
Script version

And now bashew list them in exactly that order:

```
> bashew -v -h  
# Script path: ./bashew 
# Symbolic ln: ./bashew -> [bashew.sh] 
# Actual path: /Users/pforret/Code/github/bashew/bashew.sh 
# OS Version : macOS (Darwin) 11.2.1 on arm64 
# Shell type : bash - version 5.1.4(1)-release 
# Script     : bashew v1.15.1
```
